#!/usr/bin/env python3
"""Run a lightweight Convallaria project smoke test."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL_DIR = ROOT / "skills" / "convallaria"
TEXT_GLOBS = [
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "claude/**/*.md",
    ".claude/**/*.md",
    "skills/convallaria/SKILL.md",
    "skills/convallaria/routing.md",
    "skills/convallaria/subskills/*/SKILL.md",
    "skills/convallaria/subskills/*/templates/*",
    "scripts/*.py",
]


def run(command: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, check=True, text=True, capture_output=True)


def check(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def check_plugin() -> None:
    manifest_path = ROOT / ".codex-plugin" / "plugin.json"
    check(manifest_path.exists(), "Missing .codex-plugin/plugin.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    check(manifest.get("skills") == "./skills/", "Plugin manifest must expose ./skills/")
    check((SKILL_DIR / "SKILL.md").exists(), "Missing skills/convallaria/SKILL.md")


def check_claude_sync() -> None:
    pairs = [(ROOT / "CLAUDE.md", ROOT / ".claude" / "CLAUDE.md")]
    for source in sorted((ROOT / "claude" / "commands").glob("*.md")):
        pairs.append((source, ROOT / ".claude" / "commands" / source.name))

    for source, target in pairs:
        check(target.exists(), f"Missing synced Claude Code file: {target.relative_to(ROOT)}")
        check(
            source.read_text(encoding="utf-8") == target.read_text(encoding="utf-8"),
            f"Claude Code file is stale: {target.relative_to(ROOT)}",
        )

    stale = sorted((ROOT / ".claude" / "commands").glob("atelier*.md"))
    check(not stale, "Legacy Claude Code command files remain after sync")


def check_readme_logo() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    check("assets/brand/convallaria-mark.png" in readme, "README does not display assets/brand/convallaria-mark.png")
    check((ROOT / "assets" / "brand" / "convallaria-mark.png").exists(), "Missing assets/brand/convallaria-mark.png")


def check_english_sources() -> None:
    pattern = re.compile(r"[\u4e00-\u9fff]")
    for glob in TEXT_GLOBS:
        for path in ROOT.glob(glob):
            if "subskills/design-refine" in path.as_posix():
                continue
            if path.is_file():
                text = path.read_text(encoding="utf-8")
                check(not pattern.search(text), f"Non-English project text found in {path.relative_to(ROOT)}")


def check_routes() -> None:
    complete = run(
        [
            "python3",
            "scripts/route_task.py",
            "create a complete brand pack from positioning to logo, tokens, and handoff assets",
        ],
        cwd=SKILL_DIR,
    )
    complete_routes = json.loads(complete.stdout)["suggestedRoutes"]
    check(complete_routes[0]["route"] == "pack", "Complete brand pack route did not rank first")

    refine = run(
        [
            "python3",
            "scripts/route_task.py",
            "extract a design system from these screenshots and export logo pngs",
        ],
        cwd=SKILL_DIR,
    )
    refine_routes = json.loads(refine.stdout)["suggestedRoutes"]
    check(refine_routes[0]["route"] == "design-refine", "Design extraction route did not rank first")


def check_manifest_validation() -> None:
    with tempfile.TemporaryDirectory(prefix="convallaria-manifest-") as tmp:
        manifest_path = Path(tmp) / "asset-manifest.json"
        manifest = {
            "schema": "convallaria.asset-manifest.v1",
            "project": {
                "name": "Convallaria Smoke Test",
                "slug": "convallaria-smoke-test",
                "createdAt": "generated by scripts/smoke_test.py",
            },
            "inputs": [],
            "outputs": [
                {
                    "path": str(ROOT / "README.md"),
                    "role": "documentation",
                    "producer": "convallaria",
                },
                {
                    "path": str(ROOT / "assets" / "brand" / "convallaria-mark.png"),
                    "role": "brand-logo",
                    "producer": "convallaria-logo",
                },
            ],
            "qualityChecks": [
                {
                    "name": "manifest references existing files",
                    "status": "pass",
                }
            ],
            "tokens": {},
            "assets": {
                "logo": {},
                "images": {},
                "screenshots": {},
            },
            "assumptions": [],
            "openQuestions": [],
            "nextActions": [],
        }
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        run(["python3", str(SKILL_DIR / "subskills" / "export" / "scripts" / "validate_outputs.py"), str(manifest_path)])


def check_brand_logo() -> None:
    logo = ROOT / "assets" / "brand" / "convallaria-mark.png"
    if logo.suffix.lower() == ".png":
        data = logo.read_bytes()
        check(data.startswith(b"\x89PNG\r\n\x1a\n"), "Brand logo is not a valid PNG file")
        check(len(data) > 1024, "Brand logo PNG is unexpectedly small")
        return

    if logo.suffix.lower() == ".svg":
        with tempfile.TemporaryDirectory(prefix="convallaria-logo-") as tmp:
            output = Path(tmp)
            run(
                [
                    "python3",
                    str(SKILL_DIR / "subskills" / "logo" / "scripts" / "rasterize_svg.py"),
                    str(logo),
                    "--out",
                    str(output),
                    "--sizes",
                    "128",
                    "--prefix",
                    "convallaria-logo",
                ]
            )
            check((output / "convallaria-logo-128.png").exists(), "Logo raster export was not created")
        return

    raise RuntimeError(f"Unsupported logo format: {logo.suffix}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-raster", action="store_true", help="Skip SVG rasterization when the brand logo source is SVG and no renderer is installed.")
    args = parser.parse_args()

    checks = [
        ("plugin", check_plugin),
        ("claude sync", check_claude_sync),
        ("readme logo", check_readme_logo),
        ("english sources", check_english_sources),
        ("routes", check_routes),
        ("manifest", check_manifest_validation),
    ]
    if not args.skip_raster:
        checks.append(("brand logo", check_brand_logo))

    try:
        for name, fn in checks:
            fn()
            print(f"ok: {name}")
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
