#!/usr/bin/env python3
"""Run a lightweight Convallaria project smoke test."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL_DIR = ROOT / "skills" / "convallaria"
SUBSKILLS = ["audit", "concept", "images", "logo", "refine", "tokens"]
COMPAT_COMMANDS = {
    "brand": "concept",
    "optimize": "images",
}
TEXT_GLOBS = [
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "claude/**/*.md",
    ".claude/**/*.md",
    "skills/convallaria/SKILL.md",
    "skills/convallaria/agents/*.yaml",
    "skills/convallaria/routing.md",
    "skills/convallaria/shared/**/*.md",
    "skills/convallaria/shared/**/*.json",
    "skills/convallaria/shared/**/*.py",
    "skills/convallaria/subskills/*/SKILL.md",
    "skills/convallaria/subskills/*/scripts/*.py",
    "skills/convallaria/subskills/*/templates/*",
    "scripts/*.py",
]


def run(command: list[str], cwd: Path = ROOT, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, env=env, check=True, text=True, capture_output=True)


def check(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def check_plugin() -> None:
    manifest_path = ROOT / ".codex-plugin" / "plugin.json"
    check(manifest_path.exists(), "Missing .codex-plugin/plugin.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    check(manifest.get("skills") == "./skills/", "Plugin manifest must expose ./skills/")
    check((SKILL_DIR / "SKILL.md").exists(), "Missing skills/convallaria/SKILL.md")


def check_claude_sync() -> None:
    pairs = [(ROOT / "CLAUDE.md", ROOT / ".claude" / "CLAUDE.md")]
    for source in sorted((ROOT / "claude" / "commands").glob("*.md")):
        pairs.append((source, ROOT / ".claude" / "commands" / source.name))

    for source, target in pairs:
        check(target.exists(), f"Missing synced Claude Code file: {target.relative_to(ROOT)}")
        check(
            source.read_text(encoding="utf-8") == target.read_text(encoding="utf-8"),
            f"Claude Code file is stale: {target.relative_to(ROOT)}",
        )

    stale = sorted((ROOT / ".claude" / "commands").glob("atelier*.md"))
    check(not stale, "Legacy Claude Code command files remain after sync")


def check_claude_commands() -> None:
    command_dir = ROOT / "claude" / "commands"
    check((command_dir / "conva.md").exists(), "Missing base Claude Code command: conva.md")
    for subskill in SUBSKILLS:
        command = command_dir / f"conva-{subskill}.md"
        check(command.exists(), f"Missing Claude Code command for subskill: {subskill}")
        text = command.read_text(encoding="utf-8")
        check(f"subskills/{subskill}/SKILL.md" in text, f"Command conva-{subskill}.md does not route to {subskill}")

    for alias, target in COMPAT_COMMANDS.items():
        command = command_dir / f"conva-{alias}.md"
        check(command.exists(), f"Missing compatibility Claude Code command: conva-{alias}.md")
        text = command.read_text(encoding="utf-8")
        check("Alias for" in text, f"Compatibility command conva-{alias}.md must declare that it is an alias")
        check(f"subskills/{target}/SKILL.md" in text, f"Compatibility command conva-{alias}.md does not route to {target}")


def check_fresh_install() -> None:
    with tempfile.TemporaryDirectory(prefix="convallaria-home-") as tmp:
        env = os.environ.copy()
        env["HOME"] = tmp
        run(
            [
                "python3",
                "scripts/update_convallaria.py",
                "--no-codex-cachebuster",
                "--claude-scope",
                "both",
                "--codex-marketplace",
            ],
            cwd=ROOT,
            env=env,
        )

        home = Path(tmp)
        for subskill in SUBSKILLS:
            command = home / ".claude" / "commands" / f"conva-{subskill}.md"
            check(command.exists(), f"Fresh install did not create user Claude command: {command.name}")
            text = command.read_text(encoding="utf-8")
            check("Generated by Convallaria" in text, f"Fresh install command is missing managed marker: {command.name}")

        marketplace_path = home / ".agents" / "plugins" / "marketplace.json"
        check(marketplace_path.exists(), "Fresh install did not create personal Codex marketplace")
        marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
        check(marketplace.get("name") == "personal", "Fresh install marketplace must default to personal")
        entries = [entry for entry in marketplace.get("plugins", []) if entry.get("name") == "convallaria"]
        check(len(entries) == 1, "Fresh install marketplace must contain one convallaria entry")
        entry = entries[0]
        check(entry.get("source", {}).get("path") == "./plugins/convallaria", "Codex marketplace path is incorrect")
        check((home / "plugins" / "convallaria").is_symlink(), "Fresh install did not create the personal plugin symlink")


def check_readme_logo() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    check("assets/brand/convallaria-mark.png" in readme, "README does not display assets/brand/convallaria-mark.png")
    check((ROOT / "assets" / "brand" / "convallaria-mark.png").exists(), "Missing assets/brand/convallaria-mark.png")


def check_english_sources() -> None:
    pattern = re.compile(r"[\u4e00-\u9fff]")
    for glob in TEXT_GLOBS:
        for path in ROOT.glob(glob):
            if path.is_file():
                text = path.read_text(encoding="utf-8")
                check(not pattern.search(text), f"Non-English project text found in {path.relative_to(ROOT)}")


def check_routes() -> None:
    complete = run(
        [
            "python3",
            "scripts/route_task.py",
            "create a complete brand identity from positioning to logo, tokens, and handoff assets",
        ],
        cwd=SKILL_DIR,
    )
    complete_routes = json.loads(complete.stdout)["suggestedRoutes"]
    check(complete_routes[0]["route"] == "concept", "Complete brand identity route did not rank first")

    refine = run(
        [
            "python3",
            "scripts/route_task.py",
            "extract a design system from these screenshots and export logo pngs",
        ],
        cwd=SKILL_DIR,
    )
    refine_routes = json.loads(refine.stdout)["suggestedRoutes"]
    check(refine_routes[0]["route"] == "refine", "Design extraction route did not rank first")


def check_manifest_validation() -> None:
    with tempfile.TemporaryDirectory(prefix="convallaria-manifest-") as tmp:
        manifest_path = Path(tmp) / "asset-manifest.json"
        manifest = {
            "schema": "convallaria.asset-manifest.v1",
            "project": {
                "name": "Convallaria Smoke Test",
                "slug": "convallaria-smoke-test",
                "createdAt": "generated by scripts/smoke_test.py",
            },
            "inputs": [],
            "outputs": [
                {
                    "path": str(ROOT / "README.md"),
                    "role": "documentation",
                    "producer": "convallaria",
                },
                {
                    "path": str(ROOT / "assets" / "brand" / "convallaria-mark.png"),
                    "role": "brand-logo",
                    "producer": "convallaria-logo",
                },
            ],
            "qualityChecks": [
                {
                    "name": "manifest references existing files",
                    "status": "pass",
                }
            ],
            "tokens": {},
            "assets": {
                "logo": {},
                "images": {},
                "screenshots": {},
            },
            "assumptions": [],
            "openQuestions": [],
            "nextActions": [],
        }
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        run(["python3", str(SKILL_DIR / "shared" / "scripts" / "validate_outputs.py"), str(manifest_path)])


def check_token_generation() -> None:
    with tempfile.TemporaryDirectory(prefix="convallaria-tokens-") as tmp:
        out = Path(tmp) / "tokens"
        run(
            [
                "python3",
                str(SKILL_DIR / "subskills" / "tokens" / "scripts" / "generate_tokens.py"),
                str(SKILL_DIR / "subskills" / "tokens" / "templates" / "tokens-spec.json"),
                "--out",
                str(out),
            ]
        )
        for name in ["tokens.json", "tokens.css", "tailwind.extend.js", "theme.ts", "tokens.report.md"]:
            path = out / name
            check(path.exists(), f"Token generator did not create {name}")
            check(path.stat().st_size > 0, f"Token generator created empty file: {name}")


def check_brand_logo() -> None:
    logo = ROOT / "assets" / "brand" / "convallaria-mark.png"
    if logo.suffix.lower() == ".png":
        data = logo.read_bytes()
        check(data.startswith(b"\x89PNG\r\n\x1a\n"), "Brand logo is not a valid PNG file")
        check(len(data) > 1024, "Brand logo PNG is unexpectedly small")
        return

    if logo.suffix.lower() == ".svg":
        with tempfile.TemporaryDirectory(prefix="convallaria-logo-") as tmp:
            output = Path(tmp)
            run(
                [
                    "python3",
                    str(SKILL_DIR / "subskills" / "logo" / "scripts" / "rasterize_svg.py"),
                    str(logo),
                    "--out",
                    str(output),
                    "--sizes",
                    "128",
                    "--prefix",
                    "convallaria-logo",
                ]
            )
            check((output / "convallaria-logo-128.png").exists(), "Logo raster export was not created")
        return

    raise RuntimeError(f"Unsupported logo format: {logo.suffix}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-raster", action="store_true", help="Skip SVG rasterization when the brand logo source is SVG and no renderer is installed.")
    args = parser.parse_args()

    checks = [
        ("plugin", check_plugin),
        ("claude commands", check_claude_commands),
        ("claude sync", check_claude_sync),
        ("fresh install", check_fresh_install),
        ("readme logo", check_readme_logo),
        ("english sources", check_english_sources),
        ("routes", check_routes),
        ("manifest", check_manifest_validation),
        ("tokens", check_token_generation),
    ]
    if not args.skip_raster:
        checks.append(("brand logo", check_brand_logo))

    try:
        for name, fn in checks:
            fn()
            print(f"ok: {name}")
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
