#!/usr/bin/env python3
"""Refresh local Convallaria integration surfaces for Codex and Claude Code."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_JSON = ROOT / ".codex-plugin" / "plugin.json"
CLAUDE_GUIDE_SOURCE = ROOT / "CLAUDE.md"
CLAUDE_COMMAND_SOURCE = ROOT / "claude" / "commands"
CLAUDE_TARGET = ROOT / ".claude"
USER_CLAUDE_TARGET = Path.home() / ".claude"
PERSONAL_MARKETPLACE = Path.home() / ".agents" / "plugins" / "marketplace.json"
PERSONAL_PLUGIN_LINK = Path.home() / "plugins" / "convallaria"
MANAGED_MARKER = "<!-- Generated by Convallaria; edit the source checkout instead. -->"


def cachebuster() -> str:
    return datetime.now(timezone.utc).strftime("local-%Y%m%d-%H%M%S")


def refreshed_version(version: str, token: str) -> str:
    base = version.split("+", 1)[0]
    return f"{base}+codex.{token}"


def update_plugin_version(dry_run: bool = False) -> tuple[str, str]:
    data = json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))
    before = str(data.get("version", "0.1.0"))
    after = refreshed_version(before, cachebuster())
    data["version"] = after
    if not dry_run:
        PLUGIN_JSON.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return before, after


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def sync_file(source: Path, target: Path, dry_run: bool = False) -> bool:
    source_text = source.read_text(encoding="utf-8")
    current = target.read_text(encoding="utf-8") if target.exists() else None
    changed = current != source_text
    if changed and not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source_text, encoding="utf-8")
    return changed


def sync_text(text: str, target: Path, dry_run: bool = False, managed_only: bool = False) -> bool:
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if managed_only and current is not None and MANAGED_MARKER not in current:
        raise RuntimeError(
            f"Refusing to overwrite unmanaged Claude Code file: {target}. "
            "Move it aside or remove it before installing Convallaria user commands."
        )
    changed = current != text
    if changed and not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
    return changed


def user_command_text(source: Path) -> str:
    body = source.read_text(encoding="utf-8")
    return (
        f"{MANAGED_MARKER}\n"
        f"\n"
        f"Convallaria is installed from `{ROOT}`. Resolve every relative Convallaria path below from that checkout.\n"
        f"\n"
        f"{body}"
    )


def sync_claude(dry_run: bool = False) -> list[str]:
    changed = []
    if sync_file(CLAUDE_GUIDE_SOURCE, CLAUDE_TARGET / "CLAUDE.md", dry_run):
        changed.append(str(CLAUDE_TARGET / "CLAUDE.md"))

    for source in sorted(CLAUDE_COMMAND_SOURCE.glob("*.md")):
        target = CLAUDE_TARGET / "commands" / source.name
        if sync_file(source, target, dry_run):
            changed.append(str(target))
    return changed


def sync_user_claude(dry_run: bool = False) -> list[str]:
    changed = []
    for source in sorted(CLAUDE_COMMAND_SOURCE.glob("*.md")):
        target = USER_CLAUDE_TARGET / "commands" / source.name
        if sync_text(user_command_text(source), target, dry_run, managed_only=True):
            changed.append(str(target))
    return changed


def marketplace_entry() -> dict[str, object]:
    return {
        "name": "convallaria",
        "source": {
            "source": "local",
            "path": "./plugins/convallaria",
        },
        "policy": {
            "installation": "AVAILABLE",
            "authentication": "ON_INSTALL",
        },
        "category": "Productivity",
    }


def ensure_plugin_link(dry_run: bool = False) -> list[str]:
    changed = []

    if PERSONAL_PLUGIN_LINK.is_symlink():
        target = Path(os.readlink(PERSONAL_PLUGIN_LINK))
        resolved = (PERSONAL_PLUGIN_LINK.parent / target).resolve() if not target.is_absolute() else target.resolve()
        if resolved == ROOT.resolve():
            return changed
        raise RuntimeError(
            f"Refusing to replace existing symlink {PERSONAL_PLUGIN_LINK} -> {target}. "
            "Remove it or point the Codex marketplace at the intended checkout manually."
        )

    if PERSONAL_PLUGIN_LINK.exists():
        try:
            if PERSONAL_PLUGIN_LINK.resolve() == ROOT.resolve():
                return changed
        except OSError:
            pass
        raise RuntimeError(
            f"Refusing to replace existing path: {PERSONAL_PLUGIN_LINK}. "
            "Move it aside or choose a clean personal plugin location."
        )

    changed.append(str(PERSONAL_PLUGIN_LINK))
    if not dry_run:
        PERSONAL_PLUGIN_LINK.parent.mkdir(parents=True, exist_ok=True)
        PERSONAL_PLUGIN_LINK.symlink_to(ROOT, target_is_directory=True)
    return changed


def configure_personal_marketplace(dry_run: bool = False, force: bool = False) -> list[str]:
    changed = []
    changed.extend(ensure_plugin_link(dry_run))

    entry = marketplace_entry()
    if PERSONAL_MARKETPLACE.exists():
        data = json.loads(PERSONAL_MARKETPLACE.read_text(encoding="utf-8"))
    else:
        data = {
            "name": "personal",
            "interface": {
                "displayName": "Personal",
            },
            "plugins": [],
        }

    if not isinstance(data, dict):
        raise RuntimeError(f"Invalid marketplace JSON root: {PERSONAL_MARKETPLACE}")
    data.setdefault("name", "personal")
    data.setdefault("interface", {"displayName": "Personal"})
    plugins = data.setdefault("plugins", [])
    if not isinstance(plugins, list):
        raise RuntimeError(f"Invalid marketplace plugins array: {PERSONAL_MARKETPLACE}")

    existing_index = None
    for index, plugin in enumerate(plugins):
        if isinstance(plugin, dict) and plugin.get("name") == "convallaria":
            existing_index = index
            break

    if existing_index is None:
        plugins.append(entry)
        changed.append(str(PERSONAL_MARKETPLACE))
    elif plugins[existing_index] != entry:
        if not force:
            raise RuntimeError(
                f"Existing convallaria marketplace entry differs in {PERSONAL_MARKETPLACE}. "
                "Rerun with --force-codex-marketplace to replace it."
            )
        plugins[existing_index] = entry
        changed.append(str(PERSONAL_MARKETPLACE))

    if changed and not dry_run:
        PERSONAL_MARKETPLACE.parent.mkdir(parents=True, exist_ok=True)
        PERSONAL_MARKETPLACE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return changed


def marketplace_name() -> str | None:
    if not PERSONAL_MARKETPLACE.exists():
        return None

    try:
        data = json.loads(PERSONAL_MARKETPLACE.read_text(encoding="utf-8"))
    except Exception:
        return None

    name = data.get("name")
    if not isinstance(name, str) or not name:
        return None

    return name


def marketplace_hint() -> str | None:
    name = marketplace_name()
    if not name:
        return None

    try:
        data = json.loads(PERSONAL_MARKETPLACE.read_text(encoding="utf-8"))
    except Exception:
        return None

    plugins = data.get("plugins", [])
    for plugin in plugins if isinstance(plugins, list) else []:
        if not isinstance(plugin, dict) or plugin.get("name") != "convallaria":
            continue
        source = plugin.get("source", {})
        if isinstance(source, dict) and source.get("source") == "local":
            return f"codex plugin add convallaria@{name}"
    return None


def run_smoke(skip_raster: bool) -> int:
    command = ["python3", str(ROOT / "scripts" / "smoke_test.py")]
    if skip_raster:
        command.append("--skip-raster")
    return subprocess.run(command, cwd=ROOT).returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Report changes without writing files.")
    parser.add_argument("--codex-cachebuster", action="store_true", help="Update .codex-plugin/plugin.json with a local Codex cachebuster.")
    parser.add_argument("--no-codex-cachebuster", action="store_true", help="Compatibility flag; cachebusters are opt-in by default.")
    parser.add_argument("--codex-marketplace", action="store_true", help="Create or update the default personal Codex marketplace entry.")
    parser.add_argument("--force-codex-marketplace", action="store_true", help="Replace an existing convallaria entry in the personal Codex marketplace.")
    parser.add_argument("--no-claude-sync", action="store_true", help="Do not sync root CLAUDE.md and claude/commands/ into .claude/.")
    parser.add_argument(
        "--claude-scope",
        choices=["project", "user", "both"],
        default="project",
        help="Which Claude Code command surfaces to sync.",
    )
    parser.add_argument("--smoke", action="store_true", help="Run scripts/smoke_test.py after updating.")
    parser.add_argument("--skip-raster", action="store_true", help="Pass --skip-raster to the smoke test.")
    args = parser.parse_args()

    if not PLUGIN_JSON.exists():
        print(f"error: missing {PLUGIN_JSON}", file=sys.stderr)
        return 1

    if args.codex_cachebuster and not args.no_codex_cachebuster:
        before, after = update_plugin_version(args.dry_run)
        verb = "would update" if args.dry_run else "updated"
        print(f"{verb}: .codex-plugin/plugin.json version {before} -> {after}", flush=True)

    if not args.no_claude_sync and args.claude_scope in {"project", "both"}:
        changed = sync_claude(args.dry_run)
        verb = "would sync" if args.dry_run else "synced"
        if changed:
            for path in changed:
                print(f"{verb}: {display_path(Path(path))}", flush=True)
        else:
            print("ok: Claude Code files already in sync", flush=True)

    if not args.no_claude_sync and args.claude_scope in {"user", "both"}:
        changed = sync_user_claude(args.dry_run)
        verb = "would sync" if args.dry_run else "synced"
        if changed:
            for path in changed:
                print(f"{verb}: {display_path(Path(path))}", flush=True)
        else:
            print("ok: user Claude Code commands already in sync", flush=True)

    if args.codex_marketplace:
        changed = configure_personal_marketplace(args.dry_run, args.force_codex_marketplace)
        verb = "would configure" if args.dry_run else "configured"
        if changed:
            for path in changed:
                print(f"{verb}: {display_path(Path(path))}", flush=True)
        else:
            print("ok: Codex personal marketplace already points at this checkout", flush=True)

    hint = marketplace_hint()
    if hint:
        print(f"next: {hint}", flush=True)
        print("next: start a new Codex thread after reinstalling so the refreshed skill metadata is loaded", flush=True)
    else:
        print("next: run with --codex-marketplace to create the default personal Codex marketplace entry", flush=True)

    if args.smoke:
        return run_smoke(args.skip_raster)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
